# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with Black
      run: |
        black . --check -l 120
    - name: Test with unittest
      run: |
        python -m unittest discover tests -v
    - name: Check types with mypy
      run: |
        mypy . --ignore-missing-imports
